# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:

  - package-ecosystem: "npm"
    directory: "/backend"
    schedule:
      interval: "daily"
    versioning-strategy: "increase"
    open-pull-requests-limit: 5
    target-branch: "main"
    commit-message:
      prefix: "backend: "

  - package-ecosystem: "npm"
    directory: "/frontend"
    schedule:
      interval: "daily"
    versioning-strategy: "increase"
    open-pull-requests-limit: 5
    target-branch: "main"
    commit-message:
      prefix: "frontend: "

  - package-ecosystem: "gradle"
    directory: "/android"
    schedule:
      interval: "daily"
    versioning-strategy: "increase"
    open-pull-requests-limit: 5
    target-branch: "main"
    commit-message:
      prefix: "android: "