version: '3.8'

services:
  backend:
    build:
      context: ./
    ports:
      - '${APP_PORT}:3030'
    volumes:
      - ./:/app
      - /app/node_modules
    restart: always
    networks:
      - backend
  # postgres
  db:
    image: postgres:14
    ports:
      - '${DB_PORT}:5432'
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - db_data:/var/lib/postgresql/data
    restart: always
    networks:
      - backend
    healthcheck:
      test: ['CMD-SHELL', "sh -c 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}'"]
      interval: 10s
      timeout: 3s
      retries: 3

  # nginx
