### register 
POST http://192.168.31.22:3100/api/auth/register HTTP/1.1 
Content-Type: application/json

{
    "email" : "samiur.prapon@dotdot.ba", 
    "password": "12345678", 
    "type" : "student"
}

### 
POST http://192.168.31.22:3100/api/auth/login HTTP/1.1 
Content-Type: application/json

{
    "email" : "samiur.prapon@dotdot.ba", 
    "password": "12345678"
}

### 
POST http://192.168.31.22:3100/api/auth/refresh HTTP/1.1 
Content-Type: application/json 
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOiIwZjczMTA5ZC0xODJhLTQ1ZTAtYjZjOS0xYjUxY2NkM2IzYmMiLCJlbWFpbCI6InNhbWl1ci5wcmFwb25AZG90ZG90LmJhIiwidHlwZSI6InN0dWRlbnQiLCJpYXQiOjE2Mjk3Mjk5ODYsImV4cCI6MTYyOTczMjY4Nn0._f_tSAr-cvCq7nxRh2Jhdgw27QDMEq_0j3sQVZJBAYM

### 
POST http://192.168.31.22:3100/api/auth/logout HTTP/1.1 
Content-Type: application/json 
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOiIwZjczMTA5ZC0xODJhLTQ1ZTAtYjZjOS0xYjUxY2NkM2IzYmMiLCJlbWFpbCI6InNhbWl1ci5wcmFwb25AZG90ZG90LmJhIiwidHlwZSI6InN0dWRlbnQiLCJpYXQiOjE2Mjk3Mjk5ODYsImV4cCI6MTYyOTczMjY4Nn0._f_tSAr-cvCq7nxRh2Jhdgw27QDMEq_0j3sQVZJBAYM

### 
GET http://192.168.31.22:3100/api/student/
Content-Type: application/json 
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOiIwZjczMTA5ZC0xODJhLTQ1ZTAtYjZjOS0xYjUxY2NkM2IzYmMiLCJlbWFpbCI6InNhbWl1ci5wcmFwb25AZG90ZG90LmJhIiwidHlwZSI6InN0dWRlbnQiLCJpYXQiOjE2Mjk3Mjk5ODYsImV4cCI6MTYyOTczMjY4Nn0._f_tSAr-cvCq7nxRh2Jhdgw27QDMEq_0j3sQVZJBAYM

### 
POST http://192.168.31.22:3100/api/student/
Content-Type: application/json 
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOiIwZjczMTA5ZC0xODJhLTQ1ZTAtYjZjOS0xYjUxY2NkM2IzYmMiLCJlbWFpbCI6InNhbWl1ci5wcmFwb25AZG90ZG90LmJhIiwidHlwZSI6InN0dWRlbnQiLCJpYXQiOjE2Mjk3Mjk5ODYsImV4cCI6MTYyOTczMjY4Nn0._f_tSAr-cvCq7nxRh2Jhdgw27QDMEq_0j3sQVZJBAYM

{
    "studentID": "1723456798", 
    "name": "Harry Potter",
    "sex": "male"    
}

### 
GET http://192.168.31.22:3100/api/student/valid
Content-Type: application/json 
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOiIwZjczMTA5ZC0xODJhLTQ1ZTAtYjZjOS0xYjUxY2NkM2IzYmMiLCJlbWFpbCI6InNhbWl1ci5wcmFwb25AZG90ZG90LmJhIiwidHlwZSI6InN0dWRlbnQiLCJpYXQiOjE2Mjk3Mjk5ODYsImV4cCI6MTYyOTczMjY4Nn0._f_tSAr-cvCq7nxRh2Jhdgw27QDMEq_0j3sQVZJBAYM
