### Auth routes
### 
POST http://frustrated.engineer/api/auth/refresh HTTP/1.1 
Content-Type: application/json 
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOiI0Y2FmMmU5My03NTZjLTRhZDAtODY3OC1kZjMyNmUyMGQ2NzIiLCJlbWFpbCI6InNhbWl1ci5wcmFwb25AZG90ZG90LmJhIiwidHlwZSI6InN0dWRlbnQiLCJpYXQiOjE2MzAyMzgzOTksImV4cCI6MTYzMDI0MTA5OX0.1V4vbAnqJ6ALkJ8Sxlt0j2nTaBZfv_JurKxNQcXg6pc

### 
POST http://frustrated.engineer/api/auth/logout HTTP/1.1 
Content-Type: application/json 
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOiI0Y2FmMmU5My03NTZjLTRhZDAtODY3OC1kZjMyNmUyMGQ2NzIiLCJlbWFpbCI6InNhbWl1ci5wcmFwb25AZG90ZG90LmJhIiwidHlwZSI6InN0dWRlbnQiLCJpYXQiOjE2MzAyMzgzOTksImV4cCI6MTYzMDI0MTA5OX0.1V4vbAnqJ6ALkJ8Sxlt0j2nTaBZfv_JurKxNQcXg6pc


### student routes 
POST http://frustrated.engineer/api/auth/register HTTP/1.1 
Content-Type: application/json

{
    "email" : "samiur.prapon@dotdot.ba", 
    "password": "12345678", 
    "type" : "student"
}

### Student login
POST http://frustrated.engineer/api/auth/login HTTP/1.1 
Content-Type: application/json

{
    "email" : "samiur.prapon@dotdot.ba", 
    "password": "12345678"
}

### 
GET http://frustrated.engineer/api/student/
Content-Type: application/json 
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOiI1MTA0NTRhMS0yMmIyLTQxMDQtYWMzNi0yYjY1MmUzMjRmZDAiLCJlbWFpbCI6InNhbWl1ci5wcmFwb25AZG90ZG90LmJhIiwidHlwZSI6InN0dWRlbnQiLCJpYXQiOjE2MzAyODA0NTgsImV4cCI6MTYzMDI4MzE1OH0.zGrynb41NgIsay8rAX8aEz_dFEyuj7a_JoesXRkoZfg

### 
POST http://frustrated.engineer/api/student/
Content-Type: application/json 
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOiI1MTA0NTRhMS0yMmIyLTQxMDQtYWMzNi0yYjY1MmUzMjRmZDAiLCJlbWFpbCI6InNhbWl1ci5wcmFwb25AZG90ZG90LmJhIiwidHlwZSI6InN0dWRlbnQiLCJpYXQiOjE2MzAyODA0NTgsImV4cCI6MTYzMDI4MzE1OH0.zGrynb41NgIsay8rAX8aEz_dFEyuj7a_JoesXRkoZfg

{
    "studentID": "1723456798", 
    "name": "Harry Potter",
    "sex": "male"    
}

### 
GET http://frustrated.engineer/api/student/valid
Content-Type: application/json 
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOiI1MTA0NTRhMS0yMmIyLTQxMDQtYWMzNi0yYjY1MmUzMjRmZDAiLCJlbWFpbCI6InNhbWl1ci5wcmFwb25AZG90ZG90LmJhIiwidHlwZSI6InN0dWRlbnQiLCJpYXQiOjE2MzAyODA0NTgsImV4cCI6MTYzMDI4MzE1OH0.zGrynb41NgIsay8rAX8aEz_dFEyuj7a_JoesXRkoZfg

### Student course routes
### course list
GET http://frustrated.engineer/api/student/course/
Content-Type: application/json 
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOiI1MTA0NTRhMS0yMmIyLTQxMDQtYWMzNi0yYjY1MmUzMjRmZDAiLCJlbWFpbCI6InNhbWl1ci5wcmFwb25AZG90ZG90LmJhIiwidHlwZSI6InN0dWRlbnQiLCJpYXQiOjE2MzAyODA0NTgsImV4cCI6MTYzMDI4MzE1OH0.zGrynb41NgIsay8rAX8aEz_dFEyuj7a_JoesXRkoZfg


### enroll new course
POST http://frustrated.engineer/api/student/course/
Content-Type: application/json 
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOiI1MTA0NTRhMS0yMmIyLTQxMDQtYWMzNi0yYjY1MmUzMjRmZDAiLCJlbWFpbCI6InNhbWl1ci5wcmFwb25AZG90ZG90LmJhIiwidHlwZSI6InN0dWRlbnQiLCJpYXQiOjE2MzAyODA0NTgsImV4cCI6MTYzMDI4MzE1OH0.zGrynb41NgIsay8rAX8aEz_dFEyuj7a_JoesXRkoZfg

{
    "enroll": "0Oxfp2"
}

### drop course
POST http://frustrated.engineer/api/student/course/drop
Content-Type: application/json 
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOiI1MTA0NTRhMS0yMmIyLTQxMDQtYWMzNi0yYjY1MmUzMjRmZDAiLCJlbWFpbCI6InNhbWl1ci5wcmFwb25AZG90ZG90LmJhIiwidHlwZSI6InN0dWRlbnQiLCJpYXQiOjE2MzAyODA0NTgsImV4cCI6MTYzMDI4MzE1OH0.zGrynb41NgIsay8rAX8aEz_dFEyuj7a_JoesXRkoZfg

{
    "courseId": "9f260568-d64c-4e3d-8e5b-32e8dcfdfaae"
}

### Teacher routes


### Teacher registeration
POST http://frustrated.engineer/api/auth/register HTTP/1.1 
Content-Type: application/json

{
    "email" : "abc@abc.com", 
    "password": "12345678", 
    "type" : "teacher"
}

### Teacher login
POST http://frustrated.engineer/api/auth/login HTTP/1.1 
Content-Type: application/json

{
    "email" : "abc@abc.com", 
    "password": "12345678"
}


### Teacher profile
GET http://frustrated.engineer/api/teacher/
Content-Type: application/json 
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOiJlNjQ2MTVlMy1hN2I5LTQ3OGUtYTZiNi1iNDY4ZTAxNDE5ZTgiLCJlbWFpbCI6ImFiY0BhYmMuY29tIiwidHlwZSI6InRlYWNoZXIiLCJpYXQiOjE2MzAyODA1MTUsImV4cCI6MTYzMDI4MzIxNX0.5n6fbLW6eduU4xu96fHD-ihjt-rYyIS7tg9XS399Juk

### 
POST http://frustrated.engineer/api/teacher/
Content-Type: application/json 
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOiJlNjQ2MTVlMy1hN2I5LTQ3OGUtYTZiNi1iNDY4ZTAxNDE5ZTgiLCJlbWFpbCI6ImFiY0BhYmMuY29tIiwidHlwZSI6InRlYWNoZXIiLCJpYXQiOjE2MzAyODA1MTUsImV4cCI6MTYzMDI4MzIxNX0.5n6fbLW6eduU4xu96fHD-ihjt-rYyIS7tg9XS399Juk

{
    "initial": "HPR", 
    "name": "Professor Albus Dumbledore",
    "sex": "male"    
}

### 
GET http://frustrated.engineer/api/teacher/valid
Content-Type: application/json 
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOiJlNjQ2MTVlMy1hN2I5LTQ3OGUtYTZiNi1iNDY4ZTAxNDE5ZTgiLCJlbWFpbCI6ImFiY0BhYmMuY29tIiwidHlwZSI6InRlYWNoZXIiLCJpYXQiOjE2MzAyODA1MTUsImV4cCI6MTYzMDI4MzIxNX0.5n6fbLW6eduU4xu96fHD-ihjt-rYyIS7tg9XS399Juk

### Teacher course routes
### course list
GET http://frustrated.engineer/api/teacher/course/
Content-Type: application/json 
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOiJlNjQ2MTVlMy1hN2I5LTQ3OGUtYTZiNi1iNDY4ZTAxNDE5ZTgiLCJlbWFpbCI6ImFiY0BhYmMuY29tIiwidHlwZSI6InRlYWNoZXIiLCJpYXQiOjE2MzAyODA5OTksImV4cCI6MTYzMDI4MzY5OX0.8oVwDAtQsdjfHFVid4GUHzGeX8rNWbkpuR480GB5l18

### create new course
POST http://frustrated.engineer/api/teacher/course/
Content-Type: application/json 
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOiJlNjQ2MTVlMy1hN2I5LTQ3OGUtYTZiNi1iNDY4ZTAxNDE5ZTgiLCJlbWFpbCI6ImFiY0BhYmMuY29tIiwidHlwZSI6InRlYWNoZXIiLCJpYXQiOjE2MzAyODA1MTUsImV4cCI6MTYzMDI4MzIxNX0.5n6fbLW6eduU4xu96fHD-ihjt-rYyIS7tg9XS399Juk

{
    "code": "CSE427",
    "section": "1",
    "name": "Software Engineering 2",
    "semester": "Summer 2021"
}
