name: Frontend Build

on:
  pull_request:
    branches: [main, frontend]
    types: [opened, synchronize, closed]
  push:
    branches: [main, frontend]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 3

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          # cache: 'npm'
      - name: Go to directory
        run: cd ./frontend

      - name: Install Packages
        run: npm install
        working-directory: ./frontend
      
      - name: Test frontend
        run: npm run test --if-present
        working-directory: ./frontend

      - name: Build
        run: npm run build --if-present
        working-directory: ./frontend